fragment MasterGatewayFragment on Node {
  masterGateway {
    id
    serial
    state
    bootDate
    firmware
    meta {
      name
      mountingNotes
    }
    site {
      id
      name
      type
    }
  }
}
