#import "./node.gql"

query CoreNodeTreeBarControlRootNodesQuery($parentIds: [ID]) {
  rootNodes: nodes(parentIds: $parentIds) {
    ...CoreNodeTreeBarControlNodeFragment
    children {
      ...CoreNodeTreeBarControlNodeFragment
    }
  }
}
