#import "../../util/metrics.gql"

fragment AppSmokeDetectorProtocolFragment on Node {
  apartments: descendants(types: [APARTMENT]) {
    id
    name
    floor: parent {
      id
      name
    }
    devices(roles: ["SMOKE_DETECTOR"]) {
      id
      meta {
        serial
      }
      room: site {
        id
        name
      }
      ...AppSmokeDetectorMetricsFragment
    }
  }
}
